db:
  host: "172.31.26.109"
  username: "application"
  db: "appdb"
  password: "applicationP@33word"
  tablename: "incident_summary"
  updatetablename: "incident_summary_time"
  port: 3306
mongodb:
  host: "172.31.26.109"
  port: 27017
  username: "application"
  password: "application_pass_2023"
  connect: False
  database: "history"
  collection: "reports"
apis:
  geteventnotification: "http://10.0.153.141:8000/geteventnotification"
  gethournotification: "http://10.0.153.141:8000/gethournotification"
  getendofshiftnotification: "http://10.0.153.141:8000/getendofshiftnotification"
  getnotificationdetails: "http://10.0.153.141:8000/getnotificationdetails"
  postnotificationalerts: "http://172.31.26.109:7575/api/v1/mailservice/email/notification"
kafka:
  - 172.31.26.109:9092

